name: Deploy ARM Template
on: [push]

env:
  RESOURCE_GROUP: gh-actions-arm-deployment

jobs:
  deploy-arm-template:
    runs-on: ubuntu-latest
    steps:
      
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
  
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Depoy ARM Template
        uses: azure/arm-deploy@v1
         with:
          subscriptionId: ${{ secrets.SUBSCRIPTION_ID }}
          resourceGroupName: $RESOURCE_GROUP
          template: ./azuredeploy.json
          parameters: sqlAdministratorLogin=abc