name: Deploy ARM Template
on: [push]

jobs:
  deploy-arm-template:
    runs-on: ubuntu-latest
    steps:
      
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
  
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Depoy ARM Template
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.SUBSCRIPTION_ID }}
          resourceGroupName: gh-actions-arm-deployment
          template: ./azuredeploy.json
          parameters: 
            sqlAdministratorLogin=${{ secrets.SQLADMINISTRATORLOGIN }}
            sqlAdministratorLoginPassword=${{ secrets.SQLADMINISTRATORLOGINPASSWORD }}